export default {
  GET_USERS: "GET_USERS",
  GET_USERS_SINGLE: "GET_USERS_SINGLE",

  SET_USERS: "SET_USERS",
  SET_SINGLE_USER: "SET_SINGLE_USER",

  CREATE_USER: "CREATE_USER",
  GET_CURRENT_USER_POSTS: "GET_CURRENT_USER_POSTS",
  SET_CURRENT_USER_POSTS: "SET_CURRENT_USER_POSTS",
};
